In [2]:
pip install pandas

Requirement already satisfied: pandas in d:\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install requests

Requirement already satisfied: requests in d:\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\lib\site-packages (from requests) (2025.11.12)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in d:\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in d:\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import requests

In [149]:
import pandas as pd
import requests

#documento pode ser baixado em: https://basedosdados.org/dataset/37807a93-219d-45d6-b2ae-5f3f2746a035?table=3a71c300-11ce-404f-8c79-242a2c855f94

file_path = 'bq-results-20260420-020616-1776651080981.csv'

df = pd.read_csv(file_path)

In [150]:
df

,data_referencia,data_inscricao,id_imovel_receita_federal,area,status_sncr,tipo_itr,situacao_imovel,id_municipio,sigla_uf
0,2023-09-12,2022-07-28,9511534887040,30,1,NAO,2,1200401.0,AC
1,2023-09-12,2022-07-29,121061070429,691,1,NAO,2,1200807.0,AC
2,2023-09-12,2022-07-29,9501229022093,569,1,NAO,2,1200203.0,AC
3,2023-09-12,2023-04-12,120250748537,720,1,NAO,2,1200401.0,AC
4,2023-09-12,2023-04-12,120250703606,130,1,NAO,2,1200138.0,AC
...,...,...,...,...,...,...,...,...,...
199995,2023-09-12,2023-07-14,9511026728310,106,1,NAO,2,1716604.0,TO
199996,2023-09-12,2022-05-03,433680243,969,1,NAO,2,1716604.0,TO
199997,2023-09-12,2023-07-18,9241990036209,473,1,NAO,2,1706258.0,TO
199998,2023-09-12,2021-04-06,515366873,5577,1,NAO,2,1706258.0,TO
199999,2023-09-12,2022-08-02,9511377541291,223,1,NAO,2,1706258.0,TO

In [151]:
# garantir tipo numérico
df['id_municipio'] = pd.to_numeric(df['id_municipio'], errors='coerce')

# remover nulos
df = df.dropna(subset=['id_municipio'])

# ordenar por data (mais recente primeiro)
df_sorted = df.sort_values(by='data_referencia', ascending=False)

# remover duplicatas (pegar registro mais recente de cada imóvel)
df_unique = df_sorted.drop_duplicates(subset=['id_imovel_receita_federal'])

In [153]:
df_unique.shape

(91509, 9)

In [154]:
df_unique['area'].describe()

count    9.150900e+04
mean     2.004007e+03
std      1.287291e+04
min      0.000000e+00
25%      8.300000e+01
50%      2.940000e+02
75%      9.440000e+02
max      1.082391e+06
Name: area, dtype: float64

In [ ]:
# A distribuição é altamente desigual

In [157]:
#top 10 
top10 = df_unique.sort_values(by='area', ascending=False).head(10)

In [158]:
top10

,data_referencia,data_inscricao,id_imovel_receita_federal,area,status_sncr,tipo_itr,situacao_imovel,id_municipio,sigla_uf
100285,2025-02-02,2024-09-14,9999205784527,1082391,1,NAO,2,1302702.0,AM
159011,2025-10-02,2024-09-13,9050200024370,1029720,1,NAO,2,5104609.0,MT
25197,2025-09-02,2024-09-14,9501818790963,1023242,1,NAO,2,2102036.0,MA
156034,2025-10-02,2024-09-13,9040742577532,1000850,1,NAO,2,5107800.0,MT
23133,2025-09-02,2024-09-13,1140490099387,937700,1,NAO,2,2107258.0,MA
149189,2025-08-02,2024-09-13,4381030128158,834980,1,NAO,2,1400308.0,RR
167287,2025-10-02,2025-08-19,9010911130694,657999,1,NAO,2,5106299.0,MT
24075,2025-09-02,2024-09-14,9501738443146,600000,1,NAO,2,2102507.0,MA
27457,2025-09-02,2024-09-14,9999465479809,496580,1,NAO,2,2100501.0,MA
156931,2025-10-02,2024-09-13,9010160402588,480000,1,NAO,2,5103379.0,MT

In [186]:
#os 10 maiores imóveis representam X% da área total

valor_bruto = top10['area'].sum() / df_unique['area'].sum()
porcentagem = round(valor_bruto * 100)

In [187]:
porcentagem

4

In [ ]:
#os 10 maiores imóveis representam 4% da área total

In [182]:
#top 1%

top_1_percent = df_unique.sort_values(by='area', ascending=False).head(int(len(df_unique)*0.01))
valor_bruto_top1 = top_1_percent['area'].sum() / df_unique['area'].sum()
porcentagem_top_1 = round(valor_bruto_top1 *100)

In [183]:
porcentagem_top_1

37

In [ ]:
#1% dos imoveis representam 37% da área total

In [184]:
#top 5%

top_5_percent = df_unique.sort_values(by='area', ascending=False).head(int(len(df_unique)*0.05))
valor_bruto_top5 = top_5_percent['area'].sum() / df_unique['area'].sum()
porcentagem_top_5 = round(valor_bruto_top5 *100)

In [185]:
porcentagem_top_5

66

In [ ]:
#5% dos imoveis representam 37% da área total